databasePool:
  url: jdbc:mysql://localhost:3306/SomeDb
  maxPoolSize: 10
  connectionTimeoutMs: 1000
  idleTimeoutMs: 11
  maxLifetimeMs: 1800000


connections:
  kafkaBrokers: broker1:123, broker2:124